apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  application-prod.yaml: |
    spring:
      liquibase:
        enabled: false
      jpa:
        hibernate:
          ddl-auto: validate
      datasource:
        url: jdbc:postgresql://{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.name }}
        username: {{ .Values.postgresql.username }}
        password: ${SPRING_DATASOURCE_PASSWORD}

  application-migration.yaml: |
    spring:
      main:
        web-application-type: none
      liquibase:
        enabled: true
        change-log: classpath:/db/changelog/db.changelog-master.yaml
      datasource:
        url: jdbc:postgresql://{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.name }}
        username: {{ .Values.postgresql.username }}
        password: ${SPRING_DATASOURCE_PASSWORD}