apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  application-prod.yaml: |
    spring:
      liquibase:
        enabled: false
      jpa:
        hibernate:
          ddl-auto: validate
      datasource:
        url: jdbc:postgresql://{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.name }}
        username: {{ .Values.postgresql.username }}
        password: ${SPRING_DATASOURCE_PASSWORD}
    management:
      endpoint:
        health:
          show-details: always
      metrics:
        distribution:
          slo:
            http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms
          percentiles-histogram:
            http.server.requests: true
          maximum-expected-value:
           http.server.requests: 1s  
        export:
          prometheus:
            enabled: true
      endpoints:
        web:
          exposure:
            include: health, info, metrics, prometheus

  application-migration.yaml: |
    spring:
      main:
        web-application-type: none
      liquibase:
        enabled: true
        change-log: classpath:/db/changelog/db.changelog-master.yaml
      datasource:
        url: jdbc:postgresql://{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.name }}
        username: {{ .Values.postgresql.username }}
        password: ${SPRING_DATASOURCE_PASSWORD}