replicaCount: 3
image:
  repository: mshagun/user-service
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8000

ingress:
  className: nginx
  host: arch.homework
  path: /
  pathType: Prefix

postgresql:
  host: my-postgres-postgresql
  port: 5432
  database: postgres
  username: postgres
  secretName: my-postgres-postgresql

springProfiles:
  prod: prod
  migration: migration