apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: postgres-exporter
      app.kubernetes.io/name: prometheus-postgres-exporter
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scheme: http